import {
    isSingleEmojiDetector,
    is2RepeatEmojiDetector,
    is3RepeatEmojiDetector,
    is4RepeatEmojiDetector,
    is5RepeatEmojiDetector,
    is6RepeatEmojiDetector,
    is2RepeatAnimalEmojiDetector,
    is3RepeatAnimalEmojiDetector,
    is4RepeatAnimalEmojiDetector,
    is5RepeatAnimalEmojiDetector,
    is6RepeatAnimalEmojiDetector,
    is2RepeatFoodEmojiDetector,
    is3RepeatFoodEmojiDetector,
    is4RepeatFoodEmojiDetector,
    is5RepeatFoodEmojiDetector,
    is6RepeatFoodEmojiDetector,
    is2RepeatFlagEmojiDetector,
    is3RepeatFlagEmojiDetector,
    is4RepeatFlagEmojiDetector,
    is5RepeatFlagEmojiDetector,
    is6RepeatFlagEmojiDetector
} from './repeatEmoji';

export {
    isSingleEmojiDetector,
    is2RepeatEmojiDetector,
    is3RepeatEmojiDetector,
    is4RepeatEmojiDetector,
    is5RepeatEmojiDetector,
    is6RepeatEmojiDetector,
    is2RepeatAnimalEmojiDetector,
    is3RepeatAnimalEmojiDetector,
    is4RepeatAnimalEmojiDetector,
    is5RepeatAnimalEmojiDetector,
    is6RepeatAnimalEmojiDetector,
    is2RepeatFoodEmojiDetector,
    is3RepeatFoodEmojiDetector,
    is4RepeatFoodEmojiDetector,
    is5RepeatFoodEmojiDetector,
    is6RepeatFoodEmojiDetector,
    is2RepeatFlagEmojiDetector,
    is3RepeatFlagEmojiDetector,
    is4RepeatFlagEmojiDetector,
    is5RepeatFlagEmojiDetector,
    is6RepeatFlagEmojiDetector
};
